name: healthcare_profiler_v2
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.13
  - streamlit>=1.33
  - pandas>=2.0.0
  - requests>=2.31.0
  - beautifulsoup4>=4.12.0
  - rapidfuzz>=3.0.0
  - lxml>=4.9.0
  - xlsxwriter>=3.1.0
  - openpyxl>=3.1.0
  - tqdm>=4.66
  - pip
  - pip:
      - matplotlib>=3.8.0
      - seaborn>=0.12.2
